/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'unbrowse-native.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./unbrowse-native.android-arm64.node')
          } else {
            nativeBinding = require('@getfoundry/unbrowse-native-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'unbrowse-native.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./unbrowse-native.android-arm-eabi.node')
          } else {
            nativeBinding = require('@getfoundry/unbrowse-native-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'unbrowse-native.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./unbrowse-native.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@getfoundry/unbrowse-native-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'unbrowse-native.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./unbrowse-native.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@getfoundry/unbrowse-native-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'unbrowse-native.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./unbrowse-native.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@getfoundry/unbrowse-native-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'unbrowse-native.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./unbrowse-native.darwin-universal.node')
      } else {
        nativeBinding = require('@getfoundry/unbrowse-native-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'unbrowse-native.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./unbrowse-native.darwin-x64.node')
          } else {
            nativeBinding = require('@getfoundry/unbrowse-native-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'unbrowse-native.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./unbrowse-native.darwin-arm64.node')
          } else {
            nativeBinding = require('@getfoundry/unbrowse-native-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'unbrowse-native.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./unbrowse-native.freebsd-x64.node')
      } else {
        nativeBinding = require('@getfoundry/unbrowse-native-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'unbrowse-native.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./unbrowse-native.linux-x64-musl.node')
            } else {
              nativeBinding = require('@getfoundry/unbrowse-native-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'unbrowse-native.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./unbrowse-native.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@getfoundry/unbrowse-native-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'unbrowse-native.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./unbrowse-native.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@getfoundry/unbrowse-native-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'unbrowse-native.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./unbrowse-native.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@getfoundry/unbrowse-native-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'unbrowse-native.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./unbrowse-native.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@getfoundry/unbrowse-native-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'unbrowse-native.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./unbrowse-native.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@getfoundry/unbrowse-native-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'unbrowse-native.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./unbrowse-native.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@getfoundry/unbrowse-native-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'unbrowse-native.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./unbrowse-native.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@getfoundry/unbrowse-native-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'unbrowse-native.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./unbrowse-native.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@getfoundry/unbrowse-native-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

// Core module info
const { getVersion, isNative, getModuleInfo } = nativeBinding

// Parser functions
const { parseHar, isThirdPartyDomain, detectAuthMethod, getServiceName, isAuthHeader } = nativeBinding

// Auth functions
const { generateAuthJson, extractPublishableAuth, detectRefreshEndpoint, extractRefreshConfig } = nativeBinding
const { lookupKeychain, lookup1password, lookupCredentials, buildFormFields } = nativeBinding
const { vaultStore, vaultGet, vaultList, vaultDelete, vaultExportAuthJson } = nativeBinding

// Skill functions
const { generateSkill, listSkills, getSkillInfo } = nativeBinding
const { sanitizeApiTemplate, extractEndpoints, mergeEndpoints, prepareForPublish } = nativeBinding

// Browser control functions
const { browserStatus, browserStart, browserNavigate, browserSnapshot, browserAct, browserWait } = nativeBinding
const { browserGetRequests, browserGetCookies, browserGetLocalStorage, browserGetSessionStorage } = nativeBinding
const { captureFromBrowser, captureAndGenerateSkill, captureFromUrls, extractBrowserAuth } = nativeBinding
const { chromeCookiesAvailable, readChromeCookies, readChromeCookiesFull } = nativeBinding
const { testEndpoint, testGetEndpoints, validateAuth } = nativeBinding

// Marketplace functions
const { marketplaceSearch, marketplaceGetSkill, marketplaceTrending, marketplaceFeatured } = nativeBinding
const { marketplaceDownload, marketplacePublish, marketplaceTrackInstall, marketplaceTrackExecution } = nativeBinding
const { walletCreate, walletGet, walletGetOrCreate, walletSign, walletSignPayment, walletVerify, walletPubkey, walletDelete } = nativeBinding

// Workflow functions
const { recordingStart, recordingStop, recordingNavigation, recordingApiCall, recordingAction } = nativeBinding
const { recordingIsActive, recordingCurrent, recordingList, recordingLoad } = nativeBinding
const { workflowCategorize, workflowLearn, workflowExtractVariables } = nativeBinding
const { workflowExecute } = nativeBinding

// Export everything
module.exports = {
  // Core
  getVersion,
  isNative,
  getModuleInfo,

  // Parser
  parseHar,
  isThirdPartyDomain,
  detectAuthMethod,
  getServiceName,
  isAuthHeader,

  // Auth
  generateAuthJson,
  extractPublishableAuth,
  detectRefreshEndpoint,
  extractRefreshConfig,
  lookupKeychain,
  lookup1password,
  lookupCredentials,
  buildFormFields,
  vaultStore,
  vaultGet,
  vaultList,
  vaultDelete,
  vaultExportAuthJson,

  // Skill
  generateSkill,
  listSkills,
  getSkillInfo,
  sanitizeApiTemplate,
  extractEndpoints,
  mergeEndpoints,
  prepareForPublish,

  // Browser
  browserStatus,
  browserStart,
  browserNavigate,
  browserSnapshot,
  browserAct,
  browserWait,
  browserGetRequests,
  browserGetCookies,
  browserGetLocalStorage,
  browserGetSessionStorage,
  captureFromBrowser,
  captureAndGenerateSkill,
  captureFromUrls,
  extractBrowserAuth,
  chromeCookiesAvailable,
  readChromeCookies,
  readChromeCookiesFull,
  testEndpoint,
  testGetEndpoints,
  validateAuth,

  // Marketplace
  marketplaceSearch,
  marketplaceGetSkill,
  marketplaceTrending,
  marketplaceFeatured,
  marketplaceDownload,
  marketplacePublish,
  marketplaceTrackInstall,
  marketplaceTrackExecution,
  walletCreate,
  walletGet,
  walletGetOrCreate,
  walletSign,
  walletSignPayment,
  walletVerify,
  walletPubkey,
  walletDelete,

  // Workflow
  recordingStart,
  recordingStop,
  recordingNavigation,
  recordingApiCall,
  recordingAction,
  recordingIsActive,
  recordingCurrent,
  recordingList,
  recordingLoad,
  workflowCategorize,
  workflowLearn,
  workflowExtractVariables,
  workflowExecute,
}
